version: '3.9'

services:
  app:                          # Your Spring Boot service
    build: collab-image
    restart: always
    ports:
      - "3333:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/collab
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: collab
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_log:/var/log/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8300:8080"

volumes:
  postgres_data:
  postgres_log: