app:
  base:
    url: /api/v1

spring:
  application:
    name: collab-server

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/collab
    username: postgres
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  secret: b0OeNnjpZEz6fHH4n2ARL7BZKjo32wXi
  expiration: 86400000 # 1 day in milliseconds